language: node_js
sudo: false

node_js:
  - 12.16.1

branches:
  only:
    - master

addons:
  apt:
    packages:
      - google-chrome-stable

matrix:
  fast_finish: true
  allow_failures:
    - env: 'MODE=saucelabs_optional'
    - env: 'MODE=browserstack_optional'

install:
  - npm install codecov -g
  - npm install

script:
  - npm run lint
  - npm run build
  - npm run test:travis

after_success:
  - codecov -t $CODECOV_TOKEN

cache:
  directories:
    - ./node_modules
